### ISSUE TITLE
onChange is not triggered when the input value is empty string

### ISSUE THREAD

**Issue by lazazivkovic** [yury-dymov/react-bootstrap-timezone-picker#11]
Hi. First of all, thanks for the great component.

I was using it and found that if the whole input value is erased, the onChange handler does not get called. This leads to the parent component still having the old value, but the input being empty. If not everything is erased, everything works as expected (onChange gets called with empty string value).

Is there a reason for not handling null [here](https://github.com/yury-dymov/react-bootstrap-timezone-picker/blob/4744fd405e821101c91ff0161f1fe5b048f8a4c6/src/index.jsx#L111)?
If not, it could maybe be added handle this case as well?

**Comment by lazazivkovic** [comment]
@yury-dymov Opened a PR #12 for this issue. Thanks 😄

**Comment by yury-dymov** [comment]
Hey lazazivkovic, I apologize for very late response. Thank you for the contribution, merging :)
