### ISSUE TITLE
GMT offset not adjusting for daylights savings time.

### ISSUE THREAD

**Issue by ctoppel** [yury-dymov/react-bootstrap-timezone-picker#15]
Currently the GMT offset is -4 for eastern standard time, but is still being displayed as -5. This is due to hardcoded json file that isn't being updated on daylights savings time change.

**Comment by yury-dymov** [comment]
Yeah, I can't see a good solution for that given that many countries are switching timezones in different time and the library is too simple to address this. On top of that I am not using it personally and don't have time to support it.

As a workaround, you may use `timezones` prop to override the list, which will resolve the issue for you.
