### ISSUE TITLE
Error when using: Can't resolve 'react-bootstrap/FormControl'

### ISSUE THREAD

**Issue by desistud** [yury-dymov/react-bootstrap-timezone-picker#17]
I have installed this control using npm, but when I use it with version 4 of bootstrap I get the following error:

./node_modules/react-bootstrap-timezone-picker/dist/react-bootstrap-timezone-picker.min.js
Module not found: Can't resolve 'react-bootstrap/FormControl' in 'node_modules/react-bootstrap-timezone-picker/dist'

Does this work with newer version of bootstrap?

**Comment by yury-dymov** [comment]
I don't know :) I am not using react-bootstrap much these days. Previously it meant that you didn't install react-bootstrap but maybe the introduced breaking changes in new versions. If this is the case, I would gladly accept pull requests
