### ISSUE TITLE
Not working with react-bootstrap ^1.0.0?

### ISSUE THREAD

**Issue by lardois** [yury-dymov/react-bootstrap-timezone-picker#7]
Gives following error:

`Module not found: Error: Can't resolve 'react-bootstrap/lib/FormControl'`

**Comment by yury-dymov** [comment]
I will support `react-bootstrap` 1.0.0 once it will be released

**Comment by darwin2k** [comment]
@lardois   You have can an old version of react-bootstrap
"react-bootstrap": "^0.30.3",

**Comment by kimgysen** [comment]
Is there a way to use this without bootstrap? Not feeling like adding bootstrap dependency just for a picker... nice lib though.
