### ISSUE TITLE
Clicking on scrollbar causes the dropdown to close

### ISSUE THREAD

**Issue by ishan4488** [yury-dymov/react-bootstrap-timezone-picker#8]
Hi, 
Clicking on the scrollbar causes the dropdown to close.
Using the following config - 

                  <TimezonePicker
                    className={'tz-picker'}
                    absolute
                    defaultValue="Europe/Moscow"
                    placeholder="Select timezone..."
                    onChange={this.onTimeZoneChange}
                    value={currentJobDetails.timeZone}
                    timezones={allTimezones}
                  />

Happening on both chrome and firefox.

![Dropdown-closes](https://user-images.githubusercontent.com/8775247/55378086-3017bb00-5535-11e9-9d5a-8b0fd76c5327.png)

**Comment by yury-dymov** [comment]
I was not able to reproduce on chrome today. Sorry :/
